### ISSUE TITLE
Bizarre copy of CODE in B::UNOP_AUX::save (Fails to generate .c file)

### ISSUE THREAD

**Issue by toddr** [rurban/perl-compiler#280]
This output is from master but 

``` sh
$>perlcc -e 'my $z = 0; my $li2 = "c"; my $rh = { foo => [ "ok\n" ]}; print $rh->{"foo"}->[$li2+$z];' 
/usr/local/cpanel/3rdparty/perl/522-debug/bin/perlcc: Unexpected compiler output
Bizarre copy of CODE in list assignment at /usr/local/cpanel/3rdparty/perl/522-debug/lib/perl5/cpanel_lib/i386-linux-debug-64int/B/C.pm line 1467.
 CHECK failed--call queue aborted.
/usr/lib/gcc/i686-redhat-linux/4.4.7/../../../crt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
collect2: ld returned 1 exit status
```

**Comment by toddr** [comment]
op/multideref.t

**Comment by rurban** [comment]
That's because of a wrong curcv

**Comment by toddr** [comment]
We see commits but this still appears to be broken?

**Comment by rurban** [comment]
yes, still broken

**Comment by rurban** [comment]
So, we need to reify the argument in the stack somehow. $curcv . "" e.g. works fine.

**Comment by toddr** [comment]
This fixes it :(
```perl
sub curcv { print STDERR $curcv . "\n"; ;return $curcv }
```

**Comment by rurban** [comment]
It is really a normal B bug, corrupting the stack. 
This fix works because print is a LISTOP which fixes up the stack in aux_list. (the pushmark).

**Comment by atoomic** [comment]
testc.sh 280

**Comment by rurban** [comment]
Fixed with 1.52_13, tested ok with 9970b03

**Comment by toddr** [comment]
When I bisect it in our branch, it was fixed here: https://github.com/CpanelInc/perl-compiler/commit/93c128e8607ce770632fc93c8f422db272a2ba5d

**Comment by toddr** [comment]
And master was fixed by this technically cbc7f1ffb07b1f534aa76cdfc65ecd34af3b67bf

**Comment by toddr** [comment]
This is still happening. we put in a join("", 1..42) and the problem went away.

**Comment by toddr** [comment]
What I don't follow about this XS code is why/how a void function is appropriate for something that returns an array.

**Comment by rurban** [comment]
perldoc perlxs
